  
version: "3.7"

services:
    openvidu-server-kms:
        image: openvidu/openvidu-server-kms:latest
        ports:
            - "4443:4443"
        environment:
            openvidu.secret: ${OPENVIDU_SECRET}

    openvidu-teaching:
        image: diegomzmn/openviduteaching:latest
        volumes:
            - ${LOCAL_INITIAL_FILE_PATH}:${DOCKER_INITIAL_FILE_PATH}
        ports:
            - "8080:8080"
        environment:
            openvidu.url: https://${OPENVIDU_SERVER_IP}:4443/
            openvidu.secret: ${OPENVIDU_SECRET}
            initialDataFile: ${DOCKER_INITIAL_FILE_PATH}