  
version: "3.7"

services:
    openvidu-server-kms:
        image: openvidu/openvidu-server-kms:latest
        ports:
            - "4443:4443"
        environment:
            openvidu.secret: SECRET

    openvidu-teaching:
        image: diegomzmn/openviduteaching:latest
        volumes:
            - C:\Users\diego\OneDrive\Documentos\GitHub\2019-OpenViduTeaching\backend\src\main\resources\json\initialData.json:/initialData.json
        ports:
            - "8080:8080"
        environment:
            openvidu.url: https://192.168.1.38:4443/
            openvidu.secret: SECRET
            initialDataFile: /initialData.json